application:
  oauthAuthorizationUrl: "http://rabbit-dev.inquestdevops.com/auth/login"
  oauthTokenUrl: "http://rabbit-dev.inquestdevops.com/token"
  rabbitBasePath: "http://rabbit-dev.inquestdevops.com"
  port: 8080
  clientId: "test_client"
  redirectUri: "http://localhost:8080/auth/complete"
  scope: "name"
  responseType: "code"