application:
  oauthAuthorizationUrl: "http://rabbit.inquestdevops.com/auth/login"
  oauthTokenUrl: "http://rabbit.inquestdevops.com/token"
  rabbitBasePath: "http://rabbit.inquestdevops.com"
  port: 8080
  clientId: ""
  redirectUri: ""
  scope: "name"
  responseType: "code"